author:
  name: Daniel Hasselwander
  role: Software Engineer
  bio:  Roller Coaster nerd who finds joy in exploring new technologies and building projects
  location: Lexington, Kentucky

social:
  - id: "github"
    label: "GitHub"
    href: "https://github.com/djhass"
  - id: "linkedin"
    label: "Linkedin"
    href: "https://www.linkedin.com/in/daniel-hasselwander-4b8a87247/"
  - id: "email"
    label: "Email"
    href: "mailto:djhasselwander@gmail.com"